---
title: "Gapminder Wrangle"
author: "Jenna Peed"
date: "2025-10-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

install.packages("tidyverse")

library(tidyverse)

gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

head(gapminder) #shows first 6 rows
tail(gapminder) #shows last 6 rows

head(gapminder, 10) #shows first 10 rows

str(gapminder) #shows structure

ncol(gapminder) #number of columns
nrow(gapminder) #number of rows

summary(gapminder) #statistical overview

install.packages('skimr')
library(skimr)

skim(gapminder)

head(gapminder$lifeExp) #First rows of lifeExp column

#Dplyr Basics
##Main dplyr functions
###filter(): pick observations by values
###select(): pick variables by names
###mutate(): create new variables with functions of existing variables
###summarise(): collapse many values down to single summary
###arrange(): reorder rows

filter(gapminder, lifeExp < 29) #rows with life expentency less than 29

filter(gapminder, country == "Mexico")

filter(gapminder, country %in% c("Mexico", "Peru"))

select(gapminder, year, country, lifeExp)
select(gapminder, -continent, -lifeExp)

gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp)

# %>% Operator
## Shortcut: Ctrl + Shift + M
gapminder %>%  head()

gap_cambodia <- gapminder %>%  filter(country =="Cambodia")
gap_cambodia2 <- gap_cambodia %>% select(-continent, -lifeExp)

gap_cambodia <- gapminder %>% 
  filter(country == "Cambodia") %>% 
  select(-continent, -lifeExp)

gapminder %>% 
  mutate(gdp = pop * gdpPercap)

gapminder %>% 
  filter(continent == "Asia", year ==2007) %>% 
  mutate(popThousands = pop/1000) %>% 
  select(country, year, popThousands)
 
#group_by()
gapminder %>% 
  filter(year == 2002) %>% 
  group_by(continent) %>% 
  mutate(cont_pop = sum(pop))

gapminder %>% 
  group_by(continent) %>% 
  summarize(cont_pop = sum(pop)) %>% 
  ungroup()

gapminder %>% 
  group_by(continent, year) %>% 
  summarize(cont_pop = sum(pop))

gapminder %>% 
  group_by(continent, year) %>% 
  summarize(cont_pop = sum(pop)) %>% 
  arrange(year)

gapminder %>% 
  mutate(gdp = pop * gdpPercap) %>% 
  group_by(continent) %>% 
  mutate(max_gdp = max(gdp)) %>% 
  filter(gdp == max_gdp)

asia_life_exp <- gapminder %>% 
  filter(continent == "Asia") %>% 
  group_by(country) %>% 
  filter(lifeExp == max(lifeExp)) %>% 
  arrange(year)

## gapminder-wrangle.R --- baseR
## J. Lowndes lowndes@nceas.ucsb.edu


gapminder <- read.csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv', stringsAsFactors = FALSE) 
x1  <- gapminder[ , c('country', 'year', 'pop', 'gdpPercap') ]# subset columns
mex <- x1[x1$country == "Mexico", ] # subset rows
mex$gdp <- mex$pop * mex$gdpPercap # add new columns
mex$max_gdp <- max(mex$gdp)
  
