---
title: "Graphics with ggplot2"
author: "Jenna Peed"
date: "2025-10-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Learning ggplot2

install.packages("tidyverse")
library(tidyverse)

#National Parks in California
ca <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/ca.csv")

#Acadia National Park
acadia <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/acadia.csv")

#Southeast US National Parks
se <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/mass.csv")

head(ca)
ggplot(data = ca) +
  geom_point(aes(x = year, y = visitors, color =   park_name)) +
  labs( x = "Year",
        y = "Visitation",
        title = "California National Park Visitation") +
        theme_bw() +
        theme(legend.title = element_blank())

ggplot(data = se) +
  geom_point(aes(x = year, y = visitors, color = state)) +
  labs(x = "Year", y = "Visitation", title = "Southeast States National Park Visitation") +
  theme_grey()

# 2. & 3.
ggplot(data = se) +
  geom_point(aes(x = year, y = visitors, color = state)) +
  labs(x = "Year",
       y = "Visitation",
       title = "Southeast States National Park Visitation") +
  theme_light() +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 14))

#Plots of park visitation by State
ggplot(data = se) +
  geom_point(aes(x = year, y = visitors, color = park_name)) +
  facet_wrap(~ state, scales = "free")

ggplot(data = se) +
  geom_jitter(aes( x = park_name, y = visitors, color = park_name), 
  width = 0.1,
  alpha = 0.4) +
  coord_flip() +
  theme(legend.position = "none")
  
ggplot(se, aes(x = park_name, y = visitors)) + 
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(se, aes(x = year, y = visitors, color = park_name)) +
  geom_line()

#Adding multiple geoms to one plot
ggplot(data = acadia) + 
  geom_point(aes(x = year, y = visitors)) +
  geom_line(aes(x = year, y = visitors)) +
  geom_smooth(aes(x = year, y = visitors)) +
  labs(title = "Acadia National Park Visitation",
       y = "Visitation",
       x = "Year") +
  theme_bw()

ggplot(data = acadia, aes(x = year, y = visitors)) + 
  geom_point() +
  geom_line() +
  geom_smooth(color = "red") +
  labs(title = "Acadia National Park Visitation",
       y = "Visitation",
       x = "Year") +
  theme_bw()

ggplot(data = ca, aes(x = year, y = visitors, color = park_name)) +
  geom_line() +
  geom_smooth() +
  geom_jitter() +
  labs(x = "Year", y = "Visitation", title = "California National Parks Visitation")


